language: node_js
node_js: stable
cache:
    directories:
      - node_modules

branches:
    only:
        - 2020

before_install:
    - export TZ='Asia/Shanghai'

install:
    - npm install -g gitbook-cli
    - gitbook install

script:
    - gitbook build

after_script:
    - cd ./_book
    - git init
    - sed -i '$a*.md' .gitignore
    - git config user.name "qrz"
    - git config user.email "qrzbing@gmail.com"
    - git add .
    - git commit -m "first commit"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
    - git push --force --quiet https://${EE_TOKEN}@gitee.com/nuaa-pa/gitbook.git master:master